feedback:
- date: Tue, 3 Mar 2026 20:29:41 +0800
  learning: "- I prefer companies like Adyen over Fivetran as the reviews on\r\n \
    \  Glassdoor are better. I'm not as interested in career opportunities as I\r\n\
    \   don't foresee myself staying in one company as long as I have in my current\r\
    \n   one. I value culture and compensation most.\r\n   - Refrain from using em\
    \ dashes in my resumes and cover letters. While I\r\n   use them sometimes, I\
    \ understand it's noted as an artefact of AI generated\r\n   text and I don't\
    \ want to give the impression to readers that these\r\n   documents were created\
    \ lazily.\r\n   - Refrain from stretching my regional collaboration experience\
    \ as\r\n   regional leadership or regional marketing experience. I worked with\r\
    \n   colleagues from other offices and shared best practices and ideas but\r\n\
    \   wouldn't call this regional marketing.\r\n   - I am comfortable framing cross-functional\
    \ GTM work as being a conduit\r\n   between commercial leadership and marketing\
    \ teams.\r\n   - My ABM campaign had earned/ PR elements but these were managed\
    \ by our\r\n   then Brand & Comms manager.\r\n   - I don't have extensive coaching\
    \ experience. The only one I can think\r\n   of was when I coached and mentored\
    \ an intern in writing copy for an email\r\n   marketing campaign."
