listings:
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4325512549/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4328782265/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4357420999/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4367169101/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4375172020/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4355244521/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4337872169/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://jobs.smartrecruiters.com/Wise/744000111396336-senior-strategist-marketing-strategy-
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://jobs.ashbyhq.com/xbowcareers/9121b478-48fc-4226-bd74-51c30db825cd
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4375281836/
- added: '2026-03-01'
  processed: '2026-03-01'
  url: https://www.linkedin.com/jobs/view/4363202231/
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4377490862
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4364588361
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4374768161
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4375314475
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4371132625
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4375310801
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://www.linkedin.com/jobs/view/4374349790
- added: '2026-03-03'
  processed: '2026-03-03'
  url: https://jobs.denodo.com/job/Singapore-Director-of-Demand-Generation%2C-Field-and-Partner-Marketing%2C-APAC/1340081955
